package bomesmo.timer.main.core.gui;

import javax.swing.*;

public class Gui extends javax.swing.JFrame {

    /**
     * Creates new form Gui
     */
    public Gui() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblScramble = new javax.swing.JLabel();
        lblTimer = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaTempos = new javax.swing.JList<>();
        btDeletar = new javax.swing.JButton();
        btDeletarPior = new javax.swing.JButton();
        btVerSolveSelecionada = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaEstatisticas = new javax.swing.JList<>();
        btDetalharEstatistica = new javax.swing.JButton();
        seletorScramble = new javax.swing.JComboBox<>();
        painelSquare = new javax.swing.JPanel();
        seletorShapeA = new javax.swing.JComboBox<>();
        seletorShapeB = new javax.swing.JComboBox<>();
        btAddShape = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        listaAdicionados = new javax.swing.JList<>();
        deletarShapeBt = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(255, 0, 0)));

        lblScramble.setUI(MultiLineLabelUI.labelUI);
        lblScramble.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblScramble.setForeground(new java.awt.Color(255, 255, 255));
        lblScramble.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblScramble.setText("carregando...");
        lblScramble.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblTimer.setFont(new java.awt.Font("Impact", 1, 100)); // NOI18N
        lblTimer.setForeground(new java.awt.Color(255, 255, 255));
        lblTimer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTimer.setText("00:00.000");
        lblTimer.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        listaTempos.setBackground(new java.awt.Color(0, 0, 0));
        listaTempos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Solves", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N
        listaTempos.setForeground(new java.awt.Color(255, 255, 255));
        listaTempos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "[sem solves]" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaTempos.setFocusable(false);
        jScrollPane1.setViewportView(listaTempos);

        btDeletar.setText("<html>\n    <center>deletar solve<br>selecionada</center>\n</html>");
        btDeletar.setFocusable(false);

        btDeletarPior.setText("<html>\n    <center>deletar<br>pior tempo</center>\n</html>");
        btDeletarPior.setFocusable(false);

        btVerSolveSelecionada.setText("<html>\n    <center>ver solve<br>selecionada</center>\n</html>");
        btVerSolveSelecionada.setFocusable(false);

        listaEstatisticas.setBackground(new java.awt.Color(0, 0, 0));
        listaEstatisticas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Stats", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N
        listaEstatisticas.setForeground(new java.awt.Color(255, 255, 255));
        listaEstatisticas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {
                    "melhor tempo: - -",
                    "pior tempo: - -",

                    "/----------------------/",

                    "média geral: - -",
                    "average geral: - -",

                    "/----------------------/",

                    "melhor avg5: - -",
                    "current avg5: - -",
                    "pior avg5: - -",

                    "/----------------------/",

                    "melhor avg12: - -",
                    "current avg12: - -",
                    "pior avg12: - -",

                    "/----------------------/",

                    "melhor avg50: - -",
                    "current avg50: - -",
                    "pior avg50: - -",

                    "/----------------------/",

                    "melhor avg100: - -",
                    "current avg100: - -",
                    "pior avg100: - -"
            };

            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaEstatisticas.setFocusable(false);
        jScrollPane3.setViewportView(listaEstatisticas);

        btDetalharEstatistica.setText("detalhar estatística selecionada");
        btDetalharEstatistica.setFocusable(false);

        seletorScramble.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3x3", "2x2", "squareone", "squareone cúbico", "skewb", "clock", "megaminx", "megaminx LFLL" }));
        seletorScramble.setBorder(javax.swing.BorderFactory.createTitledBorder("Scramble"));
        seletorScramble.setFocusable(false);

        painelSquare.setBackground(new java.awt.Color(0, 0, 0));
        painelSquare.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cstom shapes configs", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        seletorShapeA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "carregando..." }));
        seletorShapeA.setBorder(javax.swing.BorderFactory.createTitledBorder("Shape A"));
        seletorShapeA.setFocusable(false);

        seletorShapeB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- -" }));
        seletorShapeB.setBorder(javax.swing.BorderFactory.createTitledBorder("Shape B"));
        seletorShapeB.setFocusable(false);

        btAddShape.setText("<html>\n    <center>adicionar aos<br>shapes preferidos</center>\n</html>");
        btAddShape.setFocusable(false);

        listaAdicionados.setBackground(new java.awt.Color(0, 0, 0));
        listaAdicionados.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Shapes adicionados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        listaAdicionados.setForeground(new java.awt.Color(255, 255, 255));
        listaAdicionados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "sem shapes adicionados ainda!" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaAdicionados.setFocusable(false);
        jScrollPane4.setViewportView(listaAdicionados);

        deletarShapeBt.setText("<html>deletar shape<br>selecionado</html>");
        deletarShapeBt.setActionCommand("<html>\n    <center>\n        deletar shape\n       <br>\n       selecionado\n    </center>\n</html>");
        deletarShapeBt.setFocusable(false);

        javax.swing.GroupLayout painelSquareLayout = new javax.swing.GroupLayout(painelSquare);
        painelSquare.setLayout(painelSquareLayout);
        painelSquareLayout.setHorizontalGroup(
                painelSquareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(seletorShapeA, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(seletorShapeB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btAddShape, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane4)
                        .addComponent(deletarShapeBt)
        );
        painelSquareLayout.setVerticalGroup(
                painelSquareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(painelSquareLayout.createSequentialGroup()
                                .addComponent(seletorShapeA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seletorShapeB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btAddShape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deletarShapeBt, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblScramble, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(btVerSolveSelecionada)
                                                        .addComponent(btDeletar)
                                                        .addComponent(btDeletarPior, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jScrollPane3)
                                                        .addComponent(btDetalharEstatistica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addComponent(lblTimer, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(seletorScramble, 0, 209, Short.MAX_VALUE)
                                        .addComponent(painelSquare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblScramble, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblTimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                .addComponent(btDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(9, 9, 9)
                                                                .addComponent(btDeletarPior, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(btVerSolveSelecionada, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(btDetalharEstatistica, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(seletorScramble)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(painelSquare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Sair");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    // Variables declaration - do not modify
    private javax.swing.JButton btAddShape;
    private javax.swing.JButton btDeletar;
    private javax.swing.JButton btDeletarPior;
    private javax.swing.JButton btDetalharEstatistica;
    private javax.swing.JButton btVerSolveSelecionada;
    private javax.swing.JButton deletarShapeBt;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblScramble;
    private javax.swing.JLabel lblTimer;
    private javax.swing.JList<String> listaAdicionados;
    private javax.swing.JList<String> listaEstatisticas;
    private javax.swing.JList<String> listaTempos;
    private javax.swing.JPanel painelSquare;
    private javax.swing.JComboBox<String> seletorScramble;
    private javax.swing.JComboBox<String> seletorShapeA;
    private javax.swing.JComboBox<String> seletorShapeB;
    // End of variables declaration

    public JButton getBtDeletar() {
        return btDeletar;
    }

    public JButton getBtDeletarPior() {
        return btDeletarPior;
    }

    public JButton getBtVerSolveSelecionada() {
        return btVerSolveSelecionada;
    }

    public JButton getBtDetalharEstatistica() {
        return btDetalharEstatistica;
    }

    public JButton getDeletarShapeBt() {
        return deletarShapeBt;
    }

    public JLabel getLblScramble() {
        return lblScramble;
    }

    public JLabel getLblTimer() {
        return lblTimer;
    }

    public JList<String> getListaEstatisticas() {
        return listaEstatisticas;
    }

    public JList<String> getListaTempos() {
        return listaTempos;
    }

    public JList<String> getListaAdicionados() {
        return listaAdicionados;
    }

    public JComboBox<String> getSeletorScramble() {
        return seletorScramble;
    }

    public JComboBox<String> getSeletorShapeB() {
        return seletorShapeB;
    }

    public JComboBox<String> getSeletorShapeA() {
        return seletorShapeA;
    }

    public JButton getBtAddShape() {
        return btAddShape;
    }

    public JPanel getPainelSquare() {
        return painelSquare;
    }
}